spring:

  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:todo}'
    username: postgres
    password: password

  liquibase:
    enabled: true
    change-log: 'classpath:/db/master.xml'

